# Generated by Django 5.2 on 2025-04-19 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Census',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Année')),
                ('is_projection', models.BooleanField(default=False, verbose_name='Est une projection')),
            ],
            options={
                'verbose_name': 'Recensement',
                'verbose_name_plural': 'Recensements',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='DemographicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_population', models.IntegerField(verbose_name='Population totale')),
                ('male_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pourcentage hommes')),
                ('female_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pourcentage femmes')),
                ('population_10_plus', models.IntegerField(verbose_name='Population de 10 ans et plus')),
                ('single_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taux célibataires')),
                ('married_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taux mariés')),
                ('divorced_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taux divorcés')),
                ('widowed_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taux veufs')),
                ('school_enrollment_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taux de scolarisation 6-11 ans')),
                ('illiteracy_rate_10_plus', models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Taux d'analphabétisme 10 ans et plus")),
                ('population_15_plus', models.IntegerField(verbose_name='Population de 15 ans et plus')),
                ('illiteracy_rate_15_plus', models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Taux d'analphabétisme 15 ans et plus")),
                ('census', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.census', verbose_name='Recensement')),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.commune', verbose_name='Commune')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.country', verbose_name='Pays')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.department', verbose_name='Département')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.region', verbose_name='Région')),
            ],
            options={
                'verbose_name': 'Données démographiques',
                'verbose_name_plural': 'Données démographiques',
                'unique_together': {('census', 'commune'), ('census', 'country'), ('census', 'department'), ('census', 'region')},
            },
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_education', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Aucun niveau')),
                ('preschool', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Crèche/maternelle')),
                ('primary', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Primaire')),
                ('middle_school', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Collège')),
                ('high_school', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Lycée')),
                ('university', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Université')),
                ('demographic_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.demographicdata', verbose_name='Données démographiques')),
            ],
            options={
                'verbose_name': "Niveau d'éducation",
                'verbose_name_plural': "Niveaux d'éducation",
            },
        ),
    ]
