# Generated by Django 5.2 on 2025-04-19 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_demographicdata_rural_percentage_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='demographicdata',
            unique_together={('census', 'country'), ('census', 'region', 'commune'), ('census', 'region', 'department')},
        ),
    ]
