# Generated by Django 5.2 on 2025-04-20 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_demographicdata_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='demographicdata',
            unique_together={('census', 'commune'), ('census', 'country'), ('census', 'department'), ('census', 'region')},
        ),
    ]
