# Generated by Django 5.2 on 2025-04-20 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_demographicdata_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='demographicdata',
            unique_together={('census', 'country', 'region', 'department', 'commune')},
        ),
    ]
