# Generated by Django 5.2 on 2025-06-03 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_testmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TestModel",
        ),
    ]
