# Generated by Django 5.1.7 on 2025-06-25 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_delete_testmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="DynamicTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("label", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="DynamicRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="myapp.dynamictable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DynamicColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("label", models.CharField(blank=True, max_length=200)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("string", "Texte"),
                            ("int", "Nombre entier"),
                            ("float", "Nombre décimal"),
                            ("date", "Date"),
                            ("relation", "Relation"),
                        ],
                        default="string",
                        max_length=50,
                    ),
                ),
                (
                    "related_model",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="myapp.dynamictable",
                    ),
                ),
            ],
        ),
    ]
