# Generated by Django 5.1.7 on 2025-06-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_dynamictable_dynamicrow_dynamiccolumn"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dynamicrow",
            options={
                "verbose_name": "Ligne dynamique",
                "verbose_name_plural": "Lignes dynamiques",
            },
        ),
        migrations.AlterModelOptions(
            name="dynamictable",
            options={
                "verbose_name": "Table dynamique",
                "verbose_name_plural": "Tables dynamiques",
            },
        ),
        migrations.AddField(
            model_name="dynamictable",
            name="admin_level",
            field=models.CharField(
                choices=[
                    ("country", "Pays"),
                    ("region", "Région"),
                    ("department", "Département/Moughataa"),
                    ("commune", "Commune"),
                    ("none", "Aucun niveau spécifique"),
                ],
                default="none",
                help_text="Niveau administratif auquel cette table est liée",
                max_length=20,
                verbose_name="Niveau administratif",
            ),
        ),
    ]
