# Generated by Django 5.1.7 on 2025-06-25 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_alter_dynamicrow_options_alter_dynamictable_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dynamiccolumn",
            options={
                "ordering": ["table", "order", "name"],
                "verbose_name": "Colonne dynamique",
                "verbose_name_plural": "Colonnes dynamiques",
            },
        ),
        migrations.AlterUniqueTogether(
            name="dynamiccolumn",
            unique_together={("table", "name")},
        ),
        migrations.RemoveField(
            model_name="dynamictable",
            name="admin_level",
        ),
        migrations.AddField(
            model_name="dynamiccolumn",
            name="order",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Ordre d'affichage"
            ),
        ),
        migrations.AddField(
            model_name="dynamiccolumn",
            name="required",
            field=models.BooleanField(default=False, verbose_name="Obligatoire"),
        ),
        migrations.AddField(
            model_name="dynamictable",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="dynamiccolumn",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("string", "Texte"),
                    ("int", "Nombre entier"),
                    ("float", "Nombre décimal"),
                    ("date", "Date"),
                    ("boolean", "Oui/Non"),
                ],
                default="string",
                max_length=50,
                verbose_name="Type de données",
            ),
        ),
        migrations.AlterField(
            model_name="dynamiccolumn",
            name="label",
            field=models.CharField(max_length=200, verbose_name="Nom d'affichage"),
        ),
        migrations.AlterField(
            model_name="dynamiccolumn",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nom technique"),
        ),
        migrations.AlterField(
            model_name="dynamiccolumn",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="columns",
                to="myapp.dynamictable",
                verbose_name="Table",
            ),
        ),
        migrations.AlterField(
            model_name="dynamictable",
            name="label",
            field=models.CharField(max_length=200, verbose_name="Nom d'affichage"),
        ),
        migrations.AlterField(
            model_name="dynamictable",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Nom technique"
            ),
        ),
        migrations.CreateModel(
            name="DynamicData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(verbose_name="Données")),
                (
                    "census",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.census",
                        verbose_name="Recensement",
                    ),
                ),
                (
                    "commune",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.commune",
                        verbose_name="Commune",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.country",
                        verbose_name="Pays",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.department",
                        verbose_name="Département",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.region",
                        verbose_name="Région",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.dynamictable",
                        verbose_name="Table",
                    ),
                ),
            ],
            options={
                "verbose_name": "Données dynamiques",
                "verbose_name_plural": "Données dynamiques",
                "ordering": ["census", "table", "region", "department", "commune"],
                "unique_together": {
                    ("census", "table", "country", "region", "department", "commune")
                },
            },
        ),
        migrations.DeleteModel(
            name="DynamicRow",
        ),
        migrations.RemoveField(
            model_name="dynamiccolumn",
            name="related_model",
        ),
    ]
