# Generated by Django 5.1.7 on 2025-06-30 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_alter_dynamiccolumn_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dynamiccolumn",
            name="default_value",
            field=models.TextField(
                blank=True, null=True, verbose_name="Valeur par défaut"
            ),
        ),
        migrations.AddField(
            model_name="dynamiccolumn",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="dynamiccolumn",
            name="help_text",
            field=models.TextField(blank=True, verbose_name="Texte d'aide"),
        ),
        migrations.AddField(
            model_name="dynamiccolumn",
            name="max_value",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Valeur maximale"
            ),
        ),
        migrations.AddField(
            model_name="dynamiccolumn",
            name="min_value",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Valeur minimale"
            ),
        ),
        migrations.AddField(
            model_name="dynamiccolumn",
            name="related_field",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Champ de relation"
            ),
        ),
        migrations.AddField(
            model_name="dynamiccolumn",
            name="related_model",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Country", "Pays"),
                    ("Region", "Région"),
                    ("Department", "Département"),
                    ("Commune", "Commune"),
                    ("Census", "Recensement"),
                ],
                max_length=100,
                null=True,
                verbose_name="Modèle lié",
            ),
        ),
        migrations.AddField(
            model_name="dynamicdata",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Créé le"
            ),
        ),
        migrations.AddField(
            model_name="dynamicdata",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AddField(
            model_name="dynamicdata",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Modifié le"
            ),
        ),
        migrations.AlterField(
            model_name="dynamiccolumn",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("string", "Texte"),
                    ("int", "Nombre entier"),
                    ("float", "Nombre décimal"),
                    ("date", "Date"),
                    ("boolean", "Oui/Non"),
                    ("relation", "Relation"),
                ],
                default="string",
                max_length=50,
                verbose_name="Type de données",
            ),
        ),
    ]
