# Generated by Django 5.1.7 on 2025-06-30 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_dynamiccolumn_default_value_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dynamicdata",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="dynamicdata",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="dynamicdata",
            name="updated_at",
        ),
    ]
